#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pako
Version  : 0.2.3
Release  : 9
URL      : https://files.pythonhosted.org/packages/96/91/bf16a2f64a6628dfbfd9218f0331fbf73655530608ddd2f8fb597fdb9458/pako-0.2.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/96/91/bf16a2f64a6628dfbfd9218f0331fbf73655530608ddd2f8fb597fdb9458/pako-0.2.3.tar.gz
Summary  : The universal package manager library
Group    : Development/Tools
License  : Apache-2.0
Requires: pako-bin = %{version}-%{release}
Requires: pako-license = %{version}-%{release}
Requires: pako-python = %{version}-%{release}
Requires: pako-python3 = %{version}-%{release}
Requires: appdirs
BuildRequires : appdirs
BuildRequires : buildreq-distutils3

%description
No detailed description available

%package bin
Summary: bin components for the pako package.
Group: Binaries
Requires: pako-license = %{version}-%{release}

%description bin
bin components for the pako package.


%package license
Summary: license components for the pako package.
Group: Default

%description license
license components for the pako package.


%package python
Summary: python components for the pako package.
Group: Default
Requires: pako-python3 = %{version}-%{release}

%description python
python components for the pako package.


%package python3
Summary: python3 components for the pako package.
Group: Default
Requires: python3-core
Provides: pypi(pako)

%description python3
python3 components for the pako package.


%prep
%setup -q -n pako-0.2.3
cd %{_builddir}/pako-0.2.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583198572
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pako
cp %{_builddir}/pako-0.2.3/LICENSE %{buildroot}/usr/share/package-licenses/pako/a6a5418b4d67d9f3a33cbf184b25ac7f9fa87d33
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)
/usr/pako/LICENSE

%files bin
%defattr(-,root,root,-)
/usr/bin/pako

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pako/a6a5418b4d67d9f3a33cbf184b25ac7f9fa87d33

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
